version: '3'

services:
  app:
    image: dev-hype-api
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    networks:
      - dev-hype
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_hype
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - dev-hype

networks:
  dev-hype:
    driver: bridge
